#!/bin/sh
set -e

echo 'Running all pre-commit checks:'
cargo fmt
cargo test --no-default-features --features core,models,utils
cargo test --no-default-features --features std,models,utils,websocket,websocket-codec
cargo test --no-default-features --features core,models,utils,websocket-std
cargo test --no-default-features --features core,models,utils,json-rpc-std
cargo test --no-default-features --features websocket-std,helpers
cargo test --all-features
cargo clippy --fix --allow-staged
cargo doc --no-deps
#cargo audit
