#!/bin/sh
set -e

echo 'Running all pre-commit checks:'
cargo fmt
cargo test --release
cargo test  --release --no-default-features --features embassy-rt,core,wallet,models,helpers,websocket,json-rpc
cargo clippy --fix --allow-staged
cargo doc --no-deps
cargo audit
