[package]
name = "xrpl-rust-macros"
version = "0.1.0"
edition = "2024"
description = "XRPL Rust Macros"
license = "ISC"

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"
